version: '2.0' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    hostname: localhost
    #container_name: angular-app
    build: angular-app
    ports:
      - 3010:4200
    volumes:
      - ./angular-app:/app
      - ./app/node_modules
    
  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database
    volumes:
      - ./express-server:/app/express
      - ./app/express/node_modules
    

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding
